### ISSUE TITLE
Inline styles and CSP

### ISSUE THREAD

**Issue by migueldemoura** [Keyamoon/svgxuse#41]
Since inline styles are used here:

https://github.com/Keyamoon/svgxuse/blob/master/svgxuse.js#L120-L123

``` js
svg.style.position = "absolute";
svg.style.width = 0;
svg.style.height = 0;
svg.style.overflow = "hidden";
```
one is forced to include `style-src: unsafe-inline` in CSP.

Would you be open to having a .css with a class for this specific case?

---

**Suggested fix:**

svgxuse.css
``` css
.svg-hide {
  overflow: hidden;
  position: absolute;
  width: 0;
  height: 0;
}
```

and change the referenced 4 lines to this:

``` js
svg.classList ? svg.classList.add('svg-hide') : svg.className += ' svg-hide';
```
